version: "3"
services:
  db:
    image: postgres:10
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

networks:
  backend:

volumes:
  db-data:
